### numpy 모듈 호출

In [1]:
import numpy as np

### numpy배열 생성

In [3]:
a = np.array(1)
a

array(1)

In [5]:
ndarr_1 = np.array([1,2,3])
print(ndarr_1)

[1 2 3]


In [6]:
ndarr_2 = np.array([1,2.0,3])
print(ndarr_2)

[1. 2. 3.]


In [8]:
ndarr_3 = np.array([1,2,'3'])
ndarr_3

array(['1', '2', '3'], dtype='<U11')

In [11]:
print(ndarr_1.dtype)
print(ndarr_2.dtype)
print(ndarr_3.dtype)

int32
float64
<U11


### 자료형 지정

In [13]:
dtype1 = np.array([1,2,3],dtype=np.int8)
print(dtype1.dtype)

int8


In [14]:
dtype2 = np.array([1,2,3], dtype=float)
print(dtype2.dtype)

float64


In [15]:
dtype4 = np.array([1, 2.1,'3'], dtype=int)
print(dtype4)
print(dtype4.dtype)

[1 2 3]
int32


### 배열의 정보 확인

In [17]:
ndarr_1.shape

(3,)

In [18]:
print(ndarr_1.ndim)

1


In [19]:
vector = np.array([1,2,3])
print(vector)
print(vector.shape)
print(vector.ndim)
print(vector.dtype)


[1 2 3]
(3,)
1
int32


In [21]:
vector = np.array([[1,2,3],[4,5,6]])
print(vector)
print(vector.shape)
print(vector.ndim)
print(vector.dtype)

[[1 2 3]
 [4 5 6]]
(2, 3)
2
int32


In [22]:
tensor = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(tensor)
print(tensor.shape)
print(tensor.ndim)
print(tensor.dtype)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)
3
int32


In [24]:
print(vector.size)
print(tensor.size)

6
12


### Question 배열 생성

In [27]:
Q = np.array([[1,2,3],[2,4,6],[3,6,9]])
print(Q)
print(Q.shape)
print(Q.ndim)
print(Q.size)


[[1 2 3]
 [2 4 6]
 [3 6 9]]
(3, 3)
2
9


### array - list 타입변환(쉽게변환된다)

In [29]:
# 리스트에서 ndarray 변환
list1 = [1,2,3]
arr11 = np.array(list1)
print(type(arr11))

<class 'numpy.ndarray'>


In [30]:
# ndarray에서 리스트로 변환
arr2 = np.array([1,2,3])
list2 = list(arr2)
print(type(list2))

<class 'list'>


In [31]:
# 주의해야 할 점
list4 = [[1,2,3,4],[5,6,7]]
arr4 = np.array(list4)
print(arr4)

[list([1, 2, 3, 4]) list([5, 6, 7])]


C:\Users\admin\AppData\Local\Temp\ipykernel_13292\2376368537.py:3: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr4 = np.array(list4)


In [35]:
turple1 =  (1,2,3)
arr = np.array(turple1)
print(arr)
print(type(arr))

[1 2 3]
<class 'numpy.ndarray'>


In [36]:
arr2 = np.array([1,2,3])
turple2 = tuple(arr2)
print(turple2)
print(type(turple2))


(1, 2, 3)
<class 'tuple'>


In [38]:
set1 = [1,2,3]
arr = np.array(set1)
print(arr)
print(type(arr))

[1 2 3]
<class 'numpy.ndarray'>


In [40]:
dict1 = {'a':1,'b':2,'c':3}
arr = np.array(dict1)
print(arr)
print(type(arr))
print(arr.size)

{'a': 1, 'b': 2, 'c': 3}
<class 'numpy.ndarray'>
1


### 배열 인덱싱

ndarray[col]

ndarray[row][col]

ndarray[rank[row][col]

In [42]:
list_ = [[[1,2],[3,4]],[[5,6],[7,8]]]

# 1.가져오기
print(list_[0][0][0])
# 4. 가져오기
print(list_[0][1][1])
# 7. 가져오기
print(list_[1][1][0])

1
4
7


In [46]:
arr_ = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
# 1 가져오기
print(arr_[0,0,0])
# 4 가져오기
print(arr_[0,1,1])
# 7 가져오기
print(arr_[1,1,0])

1
4
7


In [51]:
arr_1 = np.array([[1,2], 
                  [3,4], 
                  [5,6]])

# 0 행 가져와서 2차원 배열 만들기
#  ndarray[[row1, row2], col]
print(arr_1[[0]])

# 0,2 행 가져와서 2차원 배열 만들기
print(arr_1[[0,1],:])
print(arr_1[0,1])

# 다음 결과는 ?
print(arr_1[[0,1,2],[0,1,0]])  # row1,col1 = 0,0 /row2, col2 = 1,1 / row3, col3 = 2,0

# 같은 위치 데이터 여러 번 사용가능
print(arr_1[[0,0],[1,1]])


[[1 2]]
[[1 2]
 [3 4]]
2
[1 4 5]
[2 2]


In [52]:
arr_2 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

b = np.array([0,1,2,3])
c = np.array([0,2,0,1])

print(arr_2[b,c])

[ 1  6  7 11]


In [54]:
arr = np.array([1,2,3,4,5])
print(arr[[True,False,True,True,False]])
print(arr >= 3)

[1 3 4]
[False False  True  True  True]


In [56]:
arr = np.array([1,2,3,4,5])

arr[[arr%3 >= 0]]

C:\Users\admin\AppData\Local\Temp\ipykernel_13292\1260604545.py:3: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  arr[[arr%3 >= 0]]


array([1, 2, 3, 4, 5])

In [57]:
score = np.array([[78,91,84,89,93,65],
                 [82,87,98,79,91,73]])

print(score[0][score[0] >= 90])
print(score[0][score[1] >= 90])

[91 93]
[84 93]
